# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/coursemanagerdb?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true

# Username and password, change if needed
spring.datasource.username=root
spring.datasource.password=1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JSP View Resolver Configuration
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Server Port
server.port=8080
